import type { XMPPClient } from './xmpp';
import type { Chat } from '../../types';
import type { IChatRealTimeService } from '../../types/chat';
import { ChatEvent } from '../../types/enums';
import ProxyService from '../../Proxy';
import ChatHelpers from './Helpers';
import StreamManagement from './StreamManagement';
import PrivacyList from './PrivacyList';
import MultiUserChat from './MultiUserChat';
import AbstractChatService from '../AbstractChatService';
export default class XMPPChatService extends AbstractChatService implements IChatRealTimeService {
    onMessageErrorListener: Chat.OnMessageErrorListener;
    onSentMessageCallback: Chat.OnMessageSentListener;
    onDeliveredStatusListener: Chat.OnMessageDeliveredListener;
    onJoinOccupant: Chat.OnDialogJoinListener;
    onLeaveOccupant: Chat.OnDialogLeaveListener;
    onKickOccupant: Chat.OnDialogKickListener;
    xmppClient: XMPPClient;
    helpers: ChatHelpers;
    privacylist: PrivacyList;
    muc: MultiUserChat;
    streamManagement: StreamManagement;
    stanzasCallbacks: Chat.StanzasCallbacks;
    private xmppClientListeners;
    private connectPromise;
    private earlyIncomingMessagesQueue;
    constructor(proxy: ProxyService);
    get connectionStatus(): keyof import("@xmpp/connection").StatusEvents;
    get currentUserId(): Chat.UserId;
    connect(params: Chat.ConnectionParams): Promise<boolean>;
    ping(): Promise<void>;
    send(dialogId: Chat.DialogId | Chat.UserId, message?: Chat.MessageParams): string;
    sendSystemMessage(userId: Chat.UserId, message: Chat.SystemMessageParams): string;
    sendWebRTCSignalingMessage(userId: Chat.UserId, message: Chat.SystemMessageParams): string;
    sendIsTypingStatus(dialogId: Chat.DialogId | Chat.UserId): void;
    sendIsStopTypingStatus(dialogId: Chat.DialogId): void;
    sendDeliveredStatus(params: Chat.MessageStatusParams): void;
    sendReadStatus(params: Chat.MessageStatusParams): void;
    editMessage(params: Chat.EditMessageParams): void;
    deleteMessage(params: Chat.DeleteMessageParams): void;
    getLastUserActivity(userId: Chat.UserId): Promise<Chat.LastActivity>;
    private onLastActivityStanza;
    markActive(): void;
    markInactive(): void;
    disconnect(): Promise<boolean>;
    terminate(): void;
    private onMessage;
    private onPresence;
    private onIQ;
    private onSystemMessage;
    private onWebRTCSignalingMessage;
    private getCallExtension;
    private onMessageError;
    private postConnectActions;
    private enableCarbons;
    private setSubscriptionToUserLastActivity;
    subscribeToUserLastActivityStatus(userId: Chat.UserId): void;
    unsubscribeFromUserLastActivityStatus(userId: Chat.UserId): void;
    protected getListenerByName(name: ChatEvent): Chat.ListenerName | null;
    private addXMPPClientListener;
    private removeXMPPClientListener;
    private removeAllXMPPClientListeners;
}
//# sourceMappingURL=index.d.ts.map