import { SAMAClient } from '@sama-communications/sdk';
import ProxyService from '../../Proxy';
import AbstractChatService from '../AbstractChatService';
import BlockList from './BlockList';
import type { ConnectyCubeChat as Chat, IChatRealTimeService } from '../../types/chat';
export default class SAMAChatService extends AbstractChatService implements IChatRealTimeService {
    samaClient: SAMAClient;
    blockList: BlockList;
    currentUserNativeId: Chat.UserId;
    constructor(proxy: ProxyService);
    get connectionStatus(): string;
    get currentUserId(): Chat.UserId;
    connect(params: Chat.ConnectionParams): Promise<boolean>;
    disconnect(): Promise<boolean>;
    terminate(): void;
    private onSamaConnectedListener;
    private onSamaDisconnectListener;
    private onSamaMessageEventListener;
    private onSamaMessageListener;
    private onSamaSystemMessageListener;
    private onWebRTCSignalingSystemMessage;
    private onSamaMessageStatusListener;
    private onSamaUserLastActivityListener;
    private onSamaTypingListener;
    private onSamaMessageEditListener;
    private onSamaDeleteListener;
    private onSamaMessageReactionListener;
    ping(): Promise<void>;
    sendIsTypingStatus(dialogId: Chat.DialogId): Promise<void>;
    sendIsStopTypingStatus(dialogId: Chat.DialogId): Promise<void>;
    send(dialogId: Chat.DialogId, message: Chat.MessageParams): Promise<string>;
    sendSystemMessage(userId: Chat.UserId, message: Chat.SystemMessageParams): Promise<string>;
    sendSystemMessage(userIds: Array<Chat.UserId>, message: Chat.SystemMessageParams): Promise<string>;
    sendSystemMessage(dialogId: Chat.DialogId, message: Chat.SystemMessageParams): Promise<string>;
    sendWebRTCSignalingMessage(userId: number, message: Chat.SystemMessageParams): Promise<string>;
    sendDeliveredStatus(params: Chat.MessageStatusParams): Promise<void>;
    sendReadStatus(params: Chat.MessageStatusParams): Promise<void>;
    markDialogAsRead(params: Chat.DialogReadParams): Promise<void>;
    updateReaction(messageId: string, addReaction: string, removeReaction: string): Promise<void>;
    editMessage(params: Chat.EditMessageParams): Promise<void>;
    deleteMessage(params: Chat.DeleteMessageParams): Promise<void>;
    getLastUserActivity(userId: Chat.UserId): Promise<Chat.LastActivity>;
    subscribeToUserLastActivityStatus(userId: Chat.UserId): Promise<void>;
    unsubscribeFromUserLastActivityStatus(userId: Chat.UserId): Promise<void>;
    markActive(): Promise<void>;
    markInactive(): Promise<void>;
    private addAllSamaListeners;
    private removeAllSamaListeners;
}
//# sourceMappingURL=index.d.ts.map