import type { SAMAChat, XMPPChat } from './ConnectyCube';
export type { SAMAChat, XMPPChat };
export type * from './types';
import * as enums from './types/enums';
import ConnectyCube from './ConnectyCube';
declare const _default: ConnectyCube<XMPPChat> & {
    AddressBookUserDataType: typeof enums.AddressBookUserDataType;
    LoginProviderNames: typeof enums.LoginProviderNames;
    CallEvent: typeof enums.CallEvent;
    CallSessionState: typeof enums.CallSessionState;
    CallSessionConnectionState: typeof enums.CallSessionConnectionState;
    CallSignalingType: typeof enums.CallSignalingType;
    CallSignalingModuleIdentifier: "WebRTCVideoChat";
    CallType: typeof enums.CallType;
    PeerConnectionState: typeof enums.PeerConnectionState;
    ChatType: typeof enums.ChatType;
    ChatEvent: typeof enums.ChatEvent;
    PrivacyListAction: typeof enums.PrivacyListAction;
    ChatAPIs: typeof enums.ChatAPIs;
    ChatProtocol: typeof enums.ChatProtocol;
    JanusDebugMode: typeof enums.JanusDebugMode;
    DataPermission: typeof enums.DataPermission;
    DataPermissionAccess: typeof enums.DataPermissionAccess;
    DialogType: typeof enums.DialogType;
    LastMessageMessageStatus: typeof enums.LastMessageMessageStatus;
    DialogDateProp: typeof enums.DialogDateProp;
    DeviceInputType: typeof enums.DeviceInputType;
    JanusCallType: typeof enums.JanusCallType;
    JanusEvent: typeof enums.JanusEvent;
    JanusMediaTrackReason: typeof enums.JanusMediaTrackReason;
    ConferenceEvent: typeof enums.ConferenceEvent;
    MediaType: typeof enums.MediaType;
    MeetingDateMetric: typeof enums.MeetingDateMetric;
    ProxyMethod: typeof enums.ProxyMethod;
    ProxyType: typeof enums.ProxyType;
    NotificationChannel: typeof enums.NotificationChannel;
    DevicePlatform: typeof enums.DevicePlatform;
    PushEnvironment: typeof enums.PushEnvironment;
    ConnectyCube: typeof ConnectyCube;
};
export default _default;
//# sourceMappingURL=index.umd.d.ts.map